<div style='width: auto; float: center'/>
<table align="center">
    <tr>
        <th>
                <img src="STATIC/logoUnal.png" style='height: 150px; width: auto; object-fit: contain;float: right'/>                                		
        </th>
        <th>
                <img src="STATIC/EMC_ACI.svg" style='height: 150px; width: auto; object-fit: contain;float: right'/>		
        </th>        
    </tr>
</table>

</div>

<div >
  <h1 align="center">    Introducción a la Gestión de Activos -2028644    </h1>  
			<h2 align="center">    David L. Alvarez A, Ph.D    </h2>
			<h3 align="center">    dlalvareza@unal.edu.co      </h3>
            <h4 align="center">    Copyright (c) 2020 dlalvareza    </h4>
</div>

# IEEE 39-Bus System
![title](STATIC/AUX_EXAMPLE.svg)

## Cost of replacing assets
| Asset Type| Cost |
| --- | --- | 
| TR  | 2e4 | 
| OHL | 2.25e4 |
| CB  | 5e3|
| AUX | 2e3 |

### Neccesary libraries

In [1]:
import sys
#!pip install --upgrade XlsxWriter
#!pip install --upgrade openpyxl
#!pip install --upgrade pandas
#!pip install --upgrade inspyred
#!pip install --upgrade geopandas
#!pip install --upgrade contextily
#!pip install --upgrade tables
#!pip install --upgrade seaborn
#!pip install --upgrade bokeh 
#!pip install selenium
#!conda install -c conda-forge firefox geckodriver

In [2]:
import pandapower.networks as pn
import pandapower as pp

### Add PywerAM paths

In [3]:
net = pn.create_cigre_network_mv(with_der="all")

In [4]:
net

This pandapower network includes the following parameter tables:
   - bus (15 elements)
   - load (18 elements)
   - sgen (13 elements)
   - storage (2 elements)
   - switch (8 elements)
   - ext_grid (1 element)
   - line (15 elements)
   - trafo (2 elements)
   - bus_geodata (15 elements)

In [5]:
bus_name = []
for n in range(15):
    bus_name.append('Bus_'+str(n))
net.bus.name = bus_name

In [6]:
net.ext_grid

,name,bus,vm_pu,va_degree,in_service,s_sc_max_mva,s_sc_min_mva,rx_min,rx_max
0,None,0,1.03,0.0,True,5000.0,5000.0,0.1,0.1

In [7]:
net.trafo.name = ['TR_0_1','TR_0_12']
net.trafo

,name,std_type,hv_bus,lv_bus,sn_mva,vn_hv_kv,vn_lv_kv,vk_percent,vkr_percent,pfe_kw,...,tap_neutral,tap_min,tap_max,tap_step_percent,tap_step_degree,tap_pos,tap_phase_shifter,parallel,df,in_service
0,TR_0_1,None,0,1,25.0,110.0,20.0,12.00107,0.16,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,False,1,1.0,True
1,TR_0_12,None,0,12,25.0,110.0,20.0,12.00107,0.16,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,False,1,1.0,True

In [8]:
names = [x.replace(" ","_") for x in net.load.name.values]
net.load.name = names
net.load

,name,bus,p_mw,q_mvar,const_z_percent,const_i_percent,sn_mva,scaling,in_service,type
0,Load_R1,1,14.99400,3.044662,0.0,0.0,15.300,1.0,True,wye
1,Load_R3,3,0.27645,0.069285,0.0,0.0,0.285,1.0,True,wye
2,Load_R4,4,0.43165,0.108182,0.0,0.0,0.445,1.0,True,wye
3,Load_R5,5,0.72750,0.182329,0.0,0.0,0.750,1.0,True,wye
4,Load_R6,6,0.54805,0.137354,0.0,0.0,0.565,1.0,True,wye
5,Load_R8,8,0.58685,0.147078,0.0,0.0,0.605,1.0,True,wye
6,Load_R10,10,0.47530,0.119121,0.0,0.0,0.490,1.0,True,wye
7,Load_R11,11,0.32980,0.082656,0.0,0.0,0.340,1.0,True,wye
8,Load_R12,12,14.99400,3.044662,0.0,0.0,15.300,1.0,True,wye
9,Load_R14,14,0.20855,0.052268,0.0,0.0,0.215,1.0,True,wye
10,Load_CI1,1,4.84500,1.592474,0.0,0.0,5.100,1.0,True,wye
11,Load_CI3,3,0.22525,0.139597,0.0,0.0,0.265,1.0,True,wye
12,Load_CI7,7,0.07650,0.047410,0.0,0.0,0.090,1.0,True,wye
13,Load_CI9,9,0.57375,0.355578,0.0,0.0,0.675,1.0,True,wye
14,Load_CI10,10,0.06800,0.042143,0.0,0.0,0.080,1.0,True,wye
15,Load_CI12,12,5.01600,1.648679,0.0,0.0,5.280,1.0,True,wye
16,Load_CI13,13,0.03400,0.021071,0.0,0.0,0.040,1.0,True,wye
17,Load_CI14,14,0.33150,0.205445,0.0,0.0,0.390,1.0,True,wye

In [9]:
names = [x.replace(" ","_") for x in net.line.name.values]
names = [x.replace("-","_") for x in names]
net.line

,name,std_type,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,type,in_service
0,Line 1-2,CABLE_CIGRE_MV,1,2,2.82,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
1,Line 2-3,CABLE_CIGRE_MV,2,3,4.42,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
2,Line 3-4,CABLE_CIGRE_MV,3,4,0.61,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
3,Line 4-5,CABLE_CIGRE_MV,4,5,0.56,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
4,Line 5-6,CABLE_CIGRE_MV,5,6,1.54,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
5,Line 7-8,CABLE_CIGRE_MV,7,8,1.67,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
6,Line 8-9,CABLE_CIGRE_MV,8,9,0.32,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
7,Line 9-10,CABLE_CIGRE_MV,9,10,0.77,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
8,Line 10-11,CABLE_CIGRE_MV,10,11,0.33,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
9,Line 3-8,CABLE_CIGRE_MV,3,8,1.30,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
10,Line 12-13,OHL_CIGRE_MV,12,13,4.89,0.510,0.366,10.09679,0.0,0.195,1.0,1,ol,True
11,Line 13-14,OHL_CIGRE_MV,13,14,2.99,0.510,0.366,10.09679,0.0,0.195,1.0,1,ol,True
12,Line 6-7,CABLE_CIGRE_MV,6,7,0.24,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
13,Line 11-4,CABLE_CIGRE_MV,11,4,0.49,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
14,Line 14-8,OHL_CIGRE_MV,14,8,2.00,0.510,0.366,10.09679,0.0,0.195,1.0,1,ol,True

In [10]:
net.storage.name = ['ST_5','ST_10']
net.storage

,name,bus,p_mw,q_mvar,sn_mva,soc_percent,min_e_mwh,max_e_mwh,scaling,in_service,type,min_p_mw,max_p_mw
0,ST_5,5,0.6,0.0,0.2,NaN,0.0,NaN,1.0,True,Battery,-0.6,0.6
1,ST_10,10,0.2,0.0,0.2,NaN,0.0,NaN,1.0,True,Battery,-0.2,0.2

In [16]:
names = [x.replace(" ","_") for x in net.sgen.name.values]
net.sgen.name = names
net.sgen.replace[net.sgen.name=='WKA_7','WT_7']#='WT_7'
net.sgen

,name,bus,p_mw,q_mvar,sn_mva,scaling,in_service,type,current_source
0,PV_3,3,0.020,0.0,0.020,1.0,True,PV,True
1,PV_4,4,0.020,0.0,0.020,1.0,True,PV,True
2,PV_5,5,0.030,0.0,0.030,1.0,True,PV,True
3,PV_6,6,0.030,0.0,0.030,1.0,True,PV,True
4,PV_8,8,0.030,0.0,0.030,1.0,True,PV,True
5,PV_9,9,0.030,0.0,0.030,1.0,True,PV,True
6,PV_10,10,0.040,0.0,0.040,1.0,True,PV,True
7,PV_11,11,0.010,0.0,0.010,1.0,True,PV,True
8,WKA_7,7,1.500,0.0,1.500,1.0,True,WP,True
9,Residential_fuel_cell_1,5,0.033,0.0,0.033,1.0,True,Residential fuel cell,True
10,CHP_diesel_1,9,0.310,0.0,0.310,1.0,True,CHP diesel,True
11,Fuel_cell_1,9,0.212,0.0,0.212,1.0,True,Fuel cell,True
12,Residential_fuel_cell_2,10,0.014,0.0,0.014,1.0,True,Residential fuel cell,True

In [12]:
pp.runpp(net)

In [13]:
net.res_line

,p_from_mw,q_from_mvar,p_to_mw,q_to_mvar,pl_mw,ql_mvar,i_from_ka,i_to_ka,i_ka,vm_from_pu,va_from_degree,vm_to_pu,va_to_degree,loading_percent
0,2.953004e+00,1.328978,-2.915252e+00,-1.327027e+00,3.775154e-02,0.001950,0.094058,9.468672e-02,0.094687,0.993860,-6.113500,0.976535,-6.710869,65.301183
1,2.915252e+00,1.327027,-2.855066e+00,-1.318864e+00,6.018681e-02,0.008163,0.094687,9.565978e-02,0.095660,0.976535,-6.710869,0.949065,-7.668945,65.972259
2,2.201616e+00,0.388368,-2.197373e+00,-3.927177e-01,4.242889e-03,-0.004350,0.068000,6.805548e-02,0.068055,0.949065,-7.668945,0.946842,-7.803048,46.934814
3,1.785723e+00,0.284536,-1.783162e+00,-2.903980e-01,2.560300e-03,-0.005862,0.055130,5.517649e-02,0.055176,0.946842,-7.803048,0.945214,-7.904653,38.052753
4,5.186625e-01,0.108069,-5.180500e-01,-1.332930e-01,6.124555e-04,-0.025224,0.016181,1.636135e-02,0.016361,0.945214,-7.904653,0.943804,-7.981473,11.283691
5,1.423500e+00,-0.047410,-1.418801e+00,2.558512e-02,4.698975e-03,-0.021825,0.043280,4.325771e-02,0.043280,0.949993,-7.342941,0.946974,-7.618364,29.848275
6,1.032677e+00,0.569683,-1.032054e+00,-5.742394e-01,6.230709e-04,-0.004557,0.035952,3.603298e-02,0.036033,0.946974,-7.618364,0.946190,-7.641518,24.850331
7,1.010304e+00,0.218661,-1.009150e+00,-2.300887e-01,1.154188e-03,-0.011428,0.031537,3.162383e-02,0.031624,0.946190,-7.641518,0.944833,-7.716843,21.809541
8,3.198498e-01,0.068825,-3.198000e-01,-7.434900e-02,4.974182e-05,-0.005524,0.009996,1.003340e-02,0.010033,0.944833,-7.716843,0.944649,-7.727072,6.919585
9,1.717499e-01,0.721614,-1.707260e-01,-7.423464e-01,1.023890e-03,-0.020732,0.022562,2.322041e-02,0.023220,0.949065,-7.668945,0.946974,-7.618364,16.014076
10,5.779712e-01,0.269174,-5.754270e-01,-2.735245e-01,2.544190e-03,-0.004351,0.018403,1.847867e-02,0.018479,1.000146,-5.487100,0.995326,-5.538237,9.476242
11,5.414270e-01,0.252453,-5.400500e-01,-2.552129e-01,1.376973e-03,-0.002760,0.017326,1.737243e-02,0.017372,0.995326,-5.538237,0.992553,-5.567913,8.908939
12,1.391885e-09,-0.004061,-1.956511e-13,-6.226537e-13,1.391690e-09,-0.004061,0.000124,1.996275e-14,0.000124,0.943804,-7.981473,0.943804,-7.981513,0.085669
13,1.186395e-08,-0.008307,-6.764966e-14,-9.919938e-14,1.186389e-08,-0.008307,0.000254,3.669227e-15,0.000254,0.944649,-7.727072,0.944653,-7.727235,0.175065
14,4.044224e-09,-0.002500,5.474384e-15,5.615402e-14,4.044230e-09,-0.002500,0.000073,1.640928e-15,0.000073,0.992553,-5.567913,0.992555,-5.568098,0.037287

In [14]:
net.line

,name,std_type,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,type,in_service
0,Line 1-2,CABLE_CIGRE_MV,1,2,2.82,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
1,Line 2-3,CABLE_CIGRE_MV,2,3,4.42,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
2,Line 3-4,CABLE_CIGRE_MV,3,4,0.61,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
3,Line 4-5,CABLE_CIGRE_MV,4,5,0.56,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
4,Line 5-6,CABLE_CIGRE_MV,5,6,1.54,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
5,Line 7-8,CABLE_CIGRE_MV,7,8,1.67,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
6,Line 8-9,CABLE_CIGRE_MV,8,9,0.32,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
7,Line 9-10,CABLE_CIGRE_MV,9,10,0.77,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
8,Line 10-11,CABLE_CIGRE_MV,10,11,0.33,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
9,Line 3-8,CABLE_CIGRE_MV,3,8,1.30,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
10,Line 12-13,OHL_CIGRE_MV,12,13,4.89,0.510,0.366,10.09679,0.0,0.195,1.0,1,ol,True
11,Line 13-14,OHL_CIGRE_MV,13,14,2.99,0.510,0.366,10.09679,0.0,0.195,1.0,1,ol,True
12,Line 6-7,CABLE_CIGRE_MV,6,7,0.24,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
13,Line 11-4,CABLE_CIGRE_MV,11,4,0.49,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
14,Line 14-8,OHL_CIGRE_MV,14,8,2.00,0.510,0.366,10.09679,0.0,0.195,1.0,1,ol,True

In [15]:
pp.to_json(net, 'challege_net.json')